### ISSUE TITLE
Enhancement: Avoid runtime exception when "run" folder exists

### ISSUE THREAD

**Issue by schackartk** [siminegroup/E2EDNA2#10]
If the output directory for the current run already exists, right now an exception is produced:

```
Start automating tests one by one...
====================================
TESTING MODE #1: '2d structure'
Traceback (most recent call last):
  File "main.py", line 229, in <module>
    opendna = opendna(params)  # instantiate the class
  File "/home/ken/personal/E2EDNA2/opendna.py", line 53, in __init__
    self.setup()  # if we don't need a workdir & MMB files (eg, give a 3D structure), don't make one.
  File "/home/ken/personal/E2EDNA2/opendna.py", line 147, in setup
    os.mkdir(self.workDir)
FileExistsError: [Errno 17] File exists: '/home/ken/personal/E2EDNA2/localruns/run1'

END OF TEST #1. Results are saved to folder "run1", where:
        2d structure: in record.txt
```

An exception could be avoided by validating that the output directory does not exist, and providing a useful message such as "The output directory for this run already exists at './localrun/run1'", and an optional -f/--force flag could be provided to overwrite the output directory.

**Comment by schackartk** [comment]
#8 would solve this

**Comment by taoliu032** [comment]
Nice!
