### ISSUE TITLE
Bug: Runtime exception when params['workdir'] does not exist

### ISSUE THREAD

**Issue by schackartk** [siminegroup/E2EDNA2#9]
When the directory in the variable `params['workdir']` does not exist, the program fails at runtime:

```
Traceback (most recent call last):
  File "main.py", line 229, in <module>
    opendna = opendna(params)  # instantiate the class
  File "/home/ken/personal/E2EDNA2/opendna.py", line 53, in __init__
    self.setup()  # if we don't need a workdir & MMB files (eg, give a 3D structure), don't make one.
  File "/home/ken/personal/E2EDNA2/opendna.py", line 147, in setup
    os.mkdir(self.workDir)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ken/personal/E2EDNA2/localruns/run1'
```

This could be fixed by checking for the directory, and creating it if it does not exist:

```
if not os.path.isdir(params['workdir'])
    os.mkdir(params['workdir'])
```

**Comment by schackartk** [comment]
#8 would solve this

**Comment by taoliu032** [comment]
Nice
